version: '3'
services:
  cl-demo-db-pg:
    container_name: cl-demo-db-pg
    image: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
